Repository Wiz-trip/Wiz-trip-Back, pull requests merged in 2023-12, with the labels that each got.

#2 Spring security 구현 완료
  build.gradle
  src/main/java/com/wiztrip/config/OpenApiConfig.java
  src/main/java/com/wiztrip/config/spring_security/CorsConfig.java
  src/main/java/com/wiztrip/config/spring_security/SecurityConfig.java
  src/main/java/com/wiztrip/config/spring_security/auth/PrincipalDetails.java
  src/main/java/com/wiztrip/config/spring_security/auth/PrincipalDetailsService.java
  src/main/java/com/wiztrip/config/spring_security/dto/LoginRequestDto.java
  src/main/java/com/wiztrip/config/spring_security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/wiztrip/config/spring_security/jwt/JwtAuthorizationFilter.java
  src/main/java/com/wiztrip/config/spring_security/jwt/JwtExceptionHandlerFilter.java
  src/main/java/com/wiztrip/config/spring_security/jwt/JwtPasswordEncoder.java
  src/main/java/com/wiztrip/config/spring_security/jwt/JwtProperties.java
  src/main/java/com/wiztrip/config/spring_security/jwt/TestController.java
  src/main/java/com/wiztrip/config/spring_security/jwt/TokenUtils.java
  src/main/java/com/wiztrip/controller/JwtPasswordEncoder.java
  src/main/java/com/wiztrip/repository/UserRepository.java
Labels: enhancement

#8 FTP 문제 수정
  src/main/java/com/wiztrip/tool/Base64Tool.java
  src/main/java/com/wiztrip/tool/FtpTestController.java
  src/main/java/com/wiztrip/tool/FtpTool.java
Labels: bug

#9 Webp 변환 구현 완료
  build.gradle
  src/main/java/com/wiztrip/tool/WebpConvertTool.java
  src/main/java/com/wiztrip/tool/WebpTestController.java
Labels: enhancement

#7 Like 구현 완료
  src/main/java/com/wiztrip/controller/LikeController.java
  src/main/java/com/wiztrip/domain/LandmarkLikeEntity.java
  src/main/java/com/wiztrip/domain/LikeEntity.java
  src/main/java/com/wiztrip/domain/UserEntity.java
  src/main/java/com/wiztrip/dto/LikeDto.java
  src/main/java/com/wiztrip/repository/LandmarkLikeRepository.java
  src/main/java/com/wiztrip/repository/LikeRepository.java
  src/main/java/com/wiztrip/service/LikeService.java
Labels: enhancement

#12 예외처리 구현
  src/main/java/com/wiztrip/exception/CustomException.java
  src/main/java/com/wiztrip/exception/ErrorCode.java
  src/main/java/com/wiztrip/exception/ErrorResponse.java
  src/main/java/com/wiztrip/exception/GlobalExceptionAdvice.java
Labels: enhancement

#17 [기능 향상] ListDto class에 제네릭 적용 및 type attribute 추가
  src/main/java/com/wiztrip/dto/ListDto.java
Labels: enhancement

#18 [버그 수정 및 기능 향상] createTrip시 TripUserEntity에 Trip이 매핑되지 않는 문제 수정, Swagger example value 수정
  src/main/java/com/wiztrip/controller/TripController.java
  src/main/java/com/wiztrip/domain/TripEntity.java
  src/main/java/com/wiztrip/domain/TripUserEntity.java
  src/main/java/com/wiztrip/dto/TripDto.java
  src/main/java/com/wiztrip/mapstruct/TripMapper.java
Labels: bug, enhancement

#19 [기능 구현] 이메일 인증 구현
  build.gradle
  src/main/java/com/wiztrip/controller/EmailVerificationController.java
  src/main/java/com/wiztrip/repository/UserRepository.java
  src/main/java/com/wiztrip/service/EmailVerificationService.java
  src/main/java/com/wiztrip/tool/email/EmailProperties.java
  src/main/java/com/wiztrip/tool/email/EmailTool.java
  src/main/java/com/wiztrip/tool/file/Base64Dto.java
  src/main/java/com/wiztrip/tool/file/Base64Tool.java
  src/main/java/com/wiztrip/tool/file/FtpTestController.java
  src/main/java/com/wiztrip/tool/file/FtpTool.java
  src/main/java/com/wiztrip/tool/file/WebpConvertTool.java
  src/main/java/com/wiztrip/tool/file/WebpTestController.java
  src/main/java/com/wiztrip/tool/redis/RedisConfig.java
  src/main/java/com/wiztrip/tool/redis/RedisTool.java
Labels: enhancement

#20 회원가입 오류 수정 완료
  src/main/java/com/wiztrip/config/spring_security/auth/PrincipalDetails.java
  src/main/java/com/wiztrip/config/spring_security/auth/PrincipalDetailsService.java
  src/main/java/com/wiztrip/controller/UserController.java
  src/main/java/com/wiztrip/dto/UserRegisterDto.java
  src/main/java/com/wiztrip/repository/UserRepository.java
  src/main/java/com/wiztrip/service/UserService.java
Labels: documentation

#21 [버그 수정 및 기능 향상] Plan 생성시 오류 수정 및 Swagger 설명 추가
  src/main/java/com/wiztrip/constant/Address.java
  src/main/java/com/wiztrip/controller/PlanController.java
  src/main/java/com/wiztrip/domain/PlanEntity.java
  src/main/java/com/wiztrip/dto/PlanDto.java
  src/main/java/com/wiztrip/mapstruct/PlanMapper.java
  src/main/java/com/wiztrip/service/PlanService.java
Labels: enhancement, fix

#23 [기능 향상] 예외처리 수정
  src/main/java/com/wiztrip/exception/ErrorCode.java
  src/main/java/com/wiztrip/exception/GlobalExceptionAdvice.java
Labels: enhancement

#27 [기능 향상] memo 수정
  src/main/java/com/wiztrip/controller/MemoController.java
  src/main/java/com/wiztrip/domain/MemoEntity.java
  src/main/java/com/wiztrip/mapstruct/MemoMapper.java
  src/main/java/com/wiztrip/repository/MemoRepository.java
  src/main/java/com/wiztrip/service/MemoService.java
Labels: enhancement

#28 [기능 향상] review 수정
  src/main/java/com/wiztrip/controller/MemoController.java
  src/main/java/com/wiztrip/controller/ReviewController.java
  src/main/java/com/wiztrip/dto/ReviewDto.java
  src/main/java/com/wiztrip/exception/ErrorCode.java
  src/main/java/com/wiztrip/mapstruct/ReviewMapper.java
  src/main/java/com/wiztrip/repository/ReviewRepository.java
  src/main/java/com/wiztrip/service/ReviewService.java
Labels: enhancement
