Repository Wiz-trip/Wiz-trip-Back, pull requests merged in 2024-01, with the labels that each got.

#34 [기능 향상] review, memo 수정 / image 엔티티 추가
  src/main/java/com/wiztrip/Init.java
  src/main/java/com/wiztrip/constant/Address.java
  src/main/java/com/wiztrip/constant/Category.java
  src/main/java/com/wiztrip/constant/Image.java
  src/main/java/com/wiztrip/controller/MemoController.java
  src/main/java/com/wiztrip/controller/ReviewController.java
  src/main/java/com/wiztrip/domain/LandmarkEntity.java
  src/main/java/com/wiztrip/domain/LandmarkImageEntity.java
  src/main/java/com/wiztrip/domain/MemoEntity.java
  src/main/java/com/wiztrip/domain/ReviewEntity.java
  src/main/java/com/wiztrip/domain/ReviewImageEntity.java
  src/main/java/com/wiztrip/domain/UserEntity.java
  src/main/java/com/wiztrip/domain/UserImageEntity.java
  src/main/java/com/wiztrip/dto/LandmarkDto.java
  src/main/java/com/wiztrip/dto/MemoDto.java
  src/main/java/com/wiztrip/dto/ReviewDto.java
  src/main/java/com/wiztrip/dto/UserDto.java
  src/main/java/com/wiztrip/exception/ErrorCode.java
  src/main/java/com/wiztrip/mapstruct/LandmarkMapper.java
  src/main/java/com/wiztrip/mapstruct/MemoMapper.java
  src/main/java/com/wiztrip/mapstruct/ReviewMapper.java
  src/main/java/com/wiztrip/repository/MemoRepository.java
  src/main/java/com/wiztrip/repository/ReviewImageRepository.java
  src/main/java/com/wiztrip/repository/ReviewRepository.java
  src/main/java/com/wiztrip/service/MemoService.java
  src/main/java/com/wiztrip/service/ReviewService.java
Labels: enhancement

#37 [기능 향상 및 구현] 공유 url 생성 및 Trip 수정
  src/main/java/com/wiztrip/Init.java
  src/main/java/com/wiztrip/controller/TripController.java
  src/main/java/com/wiztrip/domain/PlanEntity.java
  src/main/java/com/wiztrip/domain/TripEntity.java
  src/main/java/com/wiztrip/domain/TripUrlEntity.java
  src/main/java/com/wiztrip/dto/PlanDto.java
  src/main/java/com/wiztrip/dto/TripDto.java
  src/main/java/com/wiztrip/exception/ErrorCode.java
  src/main/java/com/wiztrip/mapstruct/TripMapper.java
  src/main/java/com/wiztrip/repository/TripRepository.java
  src/main/java/com/wiztrip/repository/TripUrlRepository.java
  src/main/java/com/wiztrip/repository/TripUserRepository.java
  src/main/java/com/wiztrip/service/TripService.java
Labels: enhancement

#38 닉네임 증복처리
  src/main/java/com/wiztrip/controller/UserController.java
  src/main/java/com/wiztrip/dto/UserRegisterDto.java
Labels: fix

#40 nickname 중복 수정
  src/main/java/com/wiztrip/controller/UserController.java
  src/main/java/com/wiztrip/domain/UserEntity.java
  src/main/java/com/wiztrip/dto/UserRegisterDto.java
Labels: fix

#41 [기능 향상 및 구현] Image base64Dto 고려, Review 제약 조건, 마이페이지 관련 개수 반환 관련 수정
  src/main/java/com/wiztrip/Init.java
  src/main/java/com/wiztrip/controller/ReviewController.java
  src/main/java/com/wiztrip/domain/ReviewEntity.java
  src/main/java/com/wiztrip/dto/LandmarkDto.java
  src/main/java/com/wiztrip/dto/ReviewDto.java
  src/main/java/com/wiztrip/dto/UserDto.java
  src/main/java/com/wiztrip/exception/ErrorCode.java
  src/main/java/com/wiztrip/mapstruct/LandmarkMapper.java
  src/main/java/com/wiztrip/mapstruct/ReviewMapper.java
  src/main/java/com/wiztrip/repository/ReviewImageRepository.java
  src/main/java/com/wiztrip/repository/ReviewRepository.java
  src/main/java/com/wiztrip/repository/TripRepository.java
  src/main/java/com/wiztrip/service/ReviewService.java
  src/main/java/com/wiztrip/service/UserService.java
Labels: enhancement, fix

#42 signup 수정
  src/main/java/com/wiztrip/repository/UserRepository.java
  src/main/java/com/wiztrip/service/UserService.java
Labels: enhancement, fix

#44 [기능 향상] tripId, userId로 userList 추가하는 기능, 계획 중인 여행 개수 반환 기능, Trip 종료에 따른 제약 조건 추가
  src/main/java/com/wiztrip/controller/ReviewController.java
  src/main/java/com/wiztrip/controller/TripController.java
  src/main/java/com/wiztrip/dto/TripDto.java
  src/main/java/com/wiztrip/exception/ErrorCode.java
  src/main/java/com/wiztrip/mapstruct/TripMapper.java
  src/main/java/com/wiztrip/repository/TripRepository.java
  src/main/java/com/wiztrip/service/MemoService.java
  src/main/java/com/wiztrip/service/PlanService.java
  src/main/java/com/wiztrip/service/ReviewService.java
  src/main/java/com/wiztrip/service/TripService.java
Labels: enhancement, fix

#45 landmark api
  src/main/java/com/wiztrip/controller/LandmarkController.java
  src/main/java/com/wiztrip/domain/LandmarkEntity.java
  src/main/java/com/wiztrip/domain/LandmarkImageEntity.java
  src/main/java/com/wiztrip/dto/LandmarkDto.java
  src/main/java/com/wiztrip/repository/LandmarkImageRepository.java
  src/main/java/com/wiztrip/service/LandmarkService.java
  src/main/java/com/wiztrip/tourapi/ApiController.java
Labels: enhancement, fix

#46 [기능 수정] Review Post API 분리
  src/main/java/com/wiztrip/controller/ReviewController.java
  src/main/java/com/wiztrip/repository/ReviewImageRepository.java
  src/main/java/com/wiztrip/service/ReviewService.java
Labels: fix

#43 profile image 등록 및 삭제 기능 구현
  profile-pictures/test_image.jpg
  src/main/java/com/wiztrip/controller/UserController.java
  src/main/java/com/wiztrip/domain/UserImageEntity.java
  src/main/java/com/wiztrip/exception/ErrorCode.java
  src/main/java/com/wiztrip/repository/UserImageRepository.java
  src/main/java/com/wiztrip/repository/UserRepository.java
  src/main/java/com/wiztrip/service/ImageService.java
  src/main/java/com/wiztrip/service/UserService.java
  src/main/java/com/wiztrip/tool/file/Base64Service.java
Labels: enhancement, fix

#47 프로필 수정 api 추가
  src/main/java/com/wiztrip/controller/UserController.java
  src/main/java/com/wiztrip/dto/UserDto.java
  src/main/java/com/wiztrip/service/ImageService.java
Labels: enhancement, fix

#48 fixprofile
  src/main/java/com/wiztrip/service/UserService.java
Labels: fix

#49 profile fix
  src/main/java/com/wiztrip/service/UserService.java
Labels: fix
